---
- name: Create new server.
  hosts: localhost

  tasks:
    - name: Create server with SSH key.
      hetzner.hcloud.hcloud_server:
        api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
        name: tassadar
        server_type: cpx11
        image: ubuntu-20.04
        location: hel1
        ssh_keys:
          - Tassadar_Alpha
        state: present
      register: instance_data

    - name: Add host to inventory.
      add_host:
        name: "{{ instance_data.hcloud_server.ipv4_address }}"
        groups: servers

    - name: Mount a existing volume.
      hetzner.hcloud.hcloud_volume:
        name: volume-tassadar
        server: tassadar
        state: present

    - name: Update DNS records.
      community.general.cloudflare_dns:
        zone: bednarski.dev
        record: minecraft
        type: A
        value: "{{ instance_data.hcloud_server.ipv4_address }}"
        account_email: kuba07071999@gmail.com
        api_token: "{{ lookup('env', 'CLOUDFLARE_TOKEN') }}"
      register: record

- name: Provision server with minecraft.
  hosts: servers
  remote_user: root
  gather_facts: no

  tasks:
    - name: Wait for connection.
      wait_for_connection:

    - name: Install Java.
      apt:
        name: openjdk-11-jre-headless
        update_cache: yes

    - name: Creates directory.
      file:
        path: /mnt/volume-tassadar
        state: directory

    - name: Mount volume.
      command: mount -o discard,defaults /dev/disk/by-id/scsi-0HC_Volume_8819575 /mnt/volume-tassadar

    - name: Start the server.
      command: bash ./start.sh
      args:
        chdir: /mnt/volume-tassadar/minecraft
