---
- name: Create new server.
  hosts: localhost

  tasks:
    - name: Create server with SSH key.
      hetzner.hcloud.hcloud_server:
        api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
        name: tassadar
        server_type: cpx11
        image: ubuntu-20.04
        location: fsn1
        ssh_keys:
          - Tassadar_Alpha
        state: present
      register: instance_data

    - name: Add host to inventory.
      add_host:
        name: "{{ instance_data.hcloud_server.ipv4_address }}"
        groups: servers

    - name: Mount a existing volume.
      hetzner.hcloud.hcloud_volume:
        name: volume-tassadar
        server: tassadar
        automount: yes
        state: present

- name: Provision server with minecraft.
  hosts: servers
  remote_user: root

  tasks:
    - name: Wait for connection.
      wait_for_connection:

    - name: Install Java
      apt:
        name: openjdk-11-jre-headless
        update_cache: yes

    - name: Start the server
      shell: "(cd /mnt/volume-tassadar/minecarft; bash ./start.sh >/dev/null 2>&1 &)"
        poll: 0
