---
- name: Create new server.
  hosts: localhost

  tasks:
    - name: Create server with SSH key.
      hetzner.hcloud.hcloud_server:
        api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
        name: tassadar
        server_type: cpx11
        image: ubuntu-20.04
        location: fsn1
        ssh_keys:
          - Tassadar_Alpha
        state: present
      register: instance_data

    - name: Add host to inventory.
      debug:
        msg: "{{ instance_data }}"

    - name: Add host to inventory.
      add_host:
        name: "{{ instance_data.hcloud_server.ipv4_address }}"
        groups: servers

- name: Provision server with minecraft.
  hosts: servers
  remote_user: root

  tasks:
    - name: Wait for connection.
      wait_for_connection:
