---
- name: Delete server instance.
  hosts: localhost

  gather_facts: False

  tasks:
    - name: Ensure the server is removed.
      hetzner.hcloud.hcloud_server:
        api_token: "{{ lookup('env', 'secret.HCLOUD_TOKEN') }}"
        name: tassadar
        state: absent
