name: Create server instance.

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: python -m pip install hcloud

      - name: Install Ansible Galaxy
        run: ansible-galaxy collection install hetzner.hcloud

      - name: Set up SSH-Agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Run Ansible Playbook
        run: ansible-playbook playbooks/create.yml
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
