name: Create and provision Tassadar server.

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Ansible Galaxy collections
        run:  ansible-galaxy collection install hetzner.hcloud community.general

      - name: Install dependencies
        run: pip install python-dateutil hcloud 
      
      - name: Install dependencies
        run: pip3 install python-dateutil hcloud 
        
      - name: Install dependencies
        run: sudo pip install python-dateutil hcloud 
        
      - name: Install dependencies
        run: sudo pip search python-dateutil



      - name: Set up SSH-Agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Run Ansible Playbook
        run: ansible-playbook -vvv playbooks/create_tassadar.yml
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
