name: Delete server instance.

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: python -m pip install hcloud

      - name: Install Ansible Galaxy
        run: ansible-galaxy collection install hetzner.hcloud

      - name: Run Ansible Playbook
        run: ansible-playbook playbooks/delete.yml
