name: Delete server instance.

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Ansible Playbook
        run: ansible-playbook playbooks/delete.yml

      - name: Setup Tmate session
        uses: mxschmitt/action-tmate@v1
        if: failure()
