name: Destroy the existing Tassadar server.

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: python -m pip install hcloud

      - name: Install Ansible Galaxy collections
        run: ansible-galaxy collection install hetzner.hcloud

      - name: Run Ansible Playbook
        run: ansible-playbook playbooks/destroy_tassadar.yml
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
