name: Destroy the existing Tassadar server.

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ansible Galaxy collections
        run:  ansible-galaxy collection install hetzner.hcloud community.general
 
      - name: Install dependencies
        run: pip3 install python-dateutil hcloud 
        
      - name: Install dependencies
        run: pip3 install --upgrade ansible

      - name: Run Ansible Playbook
        run: ansible-playbook playbooks/destroy_tassadar.yml
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
